[package]
name = "examples"
edition = "2021"
version.workspace = true
publish.workspace = true
repository.workspace = true
license.workspace = true
description.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
typst-wasm-protocol = "0.0.2"
